helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/notes-app
    forcestring: true
  - name: image.tag
    value: main@sha256:f500f1bd1240af5f21c1c9c0910e75072cd2c55662ef177bf5761097129478fd
    forcestring: true
