helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/notes-app
    forcestring: true
  - name: image.tag
    value: main@sha256:90cb10636264053c1366d04521391eafbc9fda16ef4a7b5a740e07bc58e33e9b
    forcestring: true
